### ISSUE TITLE
is there an API to change the app icon?

### ISSUE THREAD

**Issue by bofeng** [expo/snack-sdk#1]
We are exploring the SDK, we found there are functions like `setName` and `setDescription` which you can change app's name and desc, but we failed to find a method like `setIcon`. So I am wondering is there a way to change the App's icon via the SDK? Thank you

**Comment by dikaiosune** [comment]
Hi! We're moving all issues to https://github.com/expo/expo. Please reopen there if you're still having issues. Thanks!
